### ISSUE TITLE
Speed up lookups for prob_male, prob_female

### ISSUE THREAD

**Issue by bcipolli** [JasonKessler/agefromname#2]
We have millions of lookups that we want to do; currently, it takes O(1 sec) per lookup.

Why so slow,and is there a good way to speed things up?

**Comment by JasonKessler** [comment]
Running for example,


>>> age_from_name.get_all_name_female_prob(current_year=1993, minimum_age=18)

Returns a pandas dataframe indexed on every name in the database and the probability someone with that name is female given the current year is 1993 and they were at least 18 at the time. 

You can join this to another dataframe with millions of names very quickly.
