### ISSUE TITLE
Pandas argmax() is deprecated - replace with idxmax()

### ISSUE THREAD

**Issue by ychennay** [JasonKessler/agefromname#3]
Currently when you call `agefromname.argmax('Jason', 'm')`, you'll get a 

> 
FutureWarning: 'argmax' is deprecated. Use 'idxmax' instead. The behavior of 'argmax' will be corrected to return the positional maximum in the future. Use 'series.values.argmax' to get the position of the maximum now.

It's coming from this line:
`
return self.get_estimated_counts(first_name, sex, current_year, minimum_age).argmax()`

Recommend simply replacing `argmax()` with `idxmax()`:
`
return self.get_estimated_counts(first_name, sex, current_year, minimum_age).idxmax()`

**Comment by JasonKessler** [comment]
Thanks for the heads up.  If you'd like please go ahead and make the change!

**Comment by nightlessbaron** [comment]
I tried using that, but it is now saying that : 
**attributeerror module 'numpy' has no attribute 'idxmax'**

**Comment by ychennay** [comment]
> I tried using that, but it is now saying that :
> **attributeerror module 'numpy' has no attribute 'idmax'**

The method is `idxmax`, not `idmax`.

**Comment by nightlessbaron** [comment]
Sorry, I wanted to say `idxmax`

**Comment by JasonKessler** [comment]
Crap... I forgot to mention this issue in the last update I made. Version 0.0.8 uses idxmax instead of argmax and doesn't generate a warning. If you're still seeing it, make sure you update the package to the latest version.
