### ISSUE TITLE
what does the "_birth_year_df_mask" function means in the age_from_name.py?

### ISSUE THREAD

**Issue by olivercqc** [JasonKessler/agefromname#5]
Hello, Jason! I appreciate your great work - agefromname. I'm new to Python and I'm now working on a project similar to this, so I'm studying your code but I can't understand what does the "_birth_year_df_mask" function means in the age_from_name.py! Can u explain this to me? Thank u very much!

**Comment by JasonKessler** [comment]
It's a protected function that returns a mask for the main dataframe st only the rows with the specified gender and birth year have `True` values.
